name: ChatFormat
main: me.ES359.ChatFormat.ChatFormat
version: 0.0.1
description: Testing Json chat message configuration...
author: ES96
website: https://github.com/ES359

commands:
  dev:
    description: Main command in plugin.
